# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e597e299db4855e897e6d84f337de1d95c41a3a5f339db115d122cb616ba8725f88fb73f049305b2d33ee3eb23840948759b9d149e39b40f5ae0a7e6d31fd96

test:
  secret_key_base: 50b045a07e94610fe83ca16458c2e2f75b608bfffa14fc456df766e540794daae493e75167bda2ecf8f2cd15a694bc59b3b45bdfab9a8efdb1d8ad19a0451c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
